### PR TITLE
Fixes Visual Studio build and removed generated files

### PR DESCRIPTION
**Pull request by rwmcintosh**
I can resubmit if you really wanted to keep all the generated build content in version control but I removed for my purposes.

Updated the .gitignore so that when you build in VS the output files are not shown as untracked

I added a callback ```Callback_Function_Delay``` used by ```CAN_Set_Callback_Functions```

### CODE REVIEW

**Comment by DanielMartensson** [comment]
Good! Can you try to run all the examples and see if the delay callback is working?

**Comment by rwmcintosh** [comment]
Oh yeah, I didn't see that file.

Do you want this organized so that the executable code is separate from the library code? Like, organized so there's a lib/dll, and an executable with only ```main.c```?

I guess there should be as many executables as there are examples. Each txt has a ```main()```. Each would just link with the library dll, but would be in separate exe projects.

**Comment by DanielMartensson** [comment]
> Oh yeah, I didn't see that file.
> 
> Do you want this organized so that the executable code is separate from the library code? Like, organized so there's a lib/dll, and an executable with only `main.c`?
> 
> I guess there should be as many executables as there are examples. Each txt has a `main()`. Each would just link with the library dll, but would be in separate exe projects.

@rwmcintosh I don't know if DLLs is needed because this code can be deployed onto embedded systems as well as regular computers.

**Comment by rwmcintosh** [comment]
> > Oh yeah, I didn't see that file.
> 
> > 
> 
> > Do you want this organized so that the executable code is separate from the library code? Like, organized so there's a lib/dll, and an executable with only `main.c`?
> 
> > 
> 
> > I guess there should be as many executables as there are examples. Each txt has a `main()`. Each would just link with the library dll, but would be in separate exe projects.
> 
> 
> 
> @rwmcintosh I don't know if DLLs is needed because this code can be deployed onto embedded systems as well as regular computers.

I'll create a branch and show you what I mean. It will only affect the windows binaries being created by Visual Studio. The advantage is that all the example code is compiled and it prevents them from being overlooked like I did.

**Comment by rwmcintosh** [comment]
Nah, I'm wrong, it just clutters up the C code with ```__declspec(dllexport)```.

**Pull request merged**
